cmake_minimum_required(VERSION 4.2)
project(Tema_2_POO)

set(CMAKE_CXX_STANDARD 20)

add_executable(Tema_2_POO
        main.cpp
        Exceptii.h
        Interfete.h
        DispozitivSmart.h
        DispozitivSmart.cpp
        BecRgb.h
        BecRgb.cpp
        Termostat.h
        Termostat.cpp
        CasaSmart.h
        CasaSmart.cpp
)